title: AI Conference Deadlines
description: Countdowns to top CV/ML/DM/AI conference deadlines
author: Abhishek Das

domain: "aideadlin.es"
baseurl: ""

twitter_hashtag: machinelearning
github_username: baosws
github_repo: baosws.github.io

markdown: kramdown
ga_id:

include: ['_pages']
